### ISSUE TITLE
Caches don't get updated

### ISSUE THREAD

**Issue by ghost** [Vapok/Sitecore.SharedSource.DynamicSites#2]
When I add / remove / change a dynamic site and save or publish, the sites cache is not updated. I need to restart IIS in order to see any changes which basically kills the purpose of the module.

**Comment by djanjicek** [comment]
Must my templates inherit from "Dynamic Site Definition Base" ? Please help out....

**Comment by ghost** [comment]
Must my templates inherit from "Dynamic Site Definition Base" ? Please help out....

**Comment by Vapok** [comment]
Hi djanjicek,

It appears that somehow the event argument mechanism with Sitecore changed and the usual way of accessing event arguments has changed.  This caused none of the events to work correctly, which prevented the cache's from getting updated. I'll be releasing version 1.6 soon. 

Sorry about the delay. I've had a hard time making time for this.

With regard to your other question, the "Dynamic Site Definition Base" template contains all of the fields that are needed to define a site. These fields are needed in order to correctly define sites that you create. As such, yes it is needed. However, this can be a base template to a base template, if needed. You can utilize your OWN "Site" template, that this will embed on.
